#!/bin/sh
set -eu
head -n 1 "$1" | grep -Eq '^(feat|fix|docs|test|refactor|build|chore|ci|perf|style)(\([a-z][a-z0-9-]*\))?!?: .+' || {
  echo 'Use a Conventional Commit: type(scope): summary' >&2
  exit 1
}
